// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// //  ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsGR2DsxgmV8Od4OJ53mhNTUFu6B7SGec',
    appId: '1:830880558901:web:1714c17dfb2501b1ace67c',
    messagingSenderId: '830880558901',
    projectId: 'socialapp-e4d5c',
    authDomain: 'socialapp-e4d5c.firebaseapp.com',
    storageBucket: 'socialapp-e4d5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeqMweAJZDrTdgG6R0TSxVh3LBH4gEbqk',
    appId: '1:830880558901:android:e1f001251d39b370ace67c',
    messagingSenderId: '830880558901',
    projectId: 'socialapp-e4d5c',
    storageBucket: 'socialapp-e4d5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6AKgZZp4MA5B5dii-gFI7T_FY2aO_MNY',
    appId: '1:830880558901:ios:a830de17daaa6a97ace67c',
    messagingSenderId: '830880558901',
    projectId: 'socialapp-e4d5c',
    storageBucket: 'socialapp-e4d5c.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6AKgZZp4MA5B5dii-gFI7T_FY2aO_MNY',
    appId: '1:830880558901:ios:66ec075e1d47a4deace67c',
    messagingSenderId: '830880558901',
    projectId: 'socialapp-e4d5c',
    storageBucket: 'socialapp-e4d5c.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
